PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TEMP TABLE to_delete(id INTEGER PRIMARY KEY);
INSERT INTO to_delete(id) SELECT id FROM users WHERE username != 'markus';
DELETE FROM sessions WHERE user_id IN (SELECT id FROM to_delete);
DELETE FROM support_messages WHERE user_id IN (SELECT id FROM to_delete);
DELETE FROM customer_preferences WHERE user_id IN (SELECT id FROM to_delete);
DELETE FROM chat_uploads WHERE user_id IN (SELECT id FROM to_delete);
DELETE FROM chat_usage_events WHERE user_id IN (SELECT id FROM to_delete);
DELETE FROM messages WHERE owner_user_id IN (SELECT id FROM to_delete);
DELETE FROM chat_conversations WHERE owner_user_id IN (SELECT id FROM to_delete);
DELETE FROM users WHERE id IN (SELECT id FROM to_delete);
DROP TABLE to_delete;
COMMIT;
PRAGMA foreign_keys=ON;
